---
- name: Add key
  apt_key:
    id: D68FA50FEA312927
    keyserver: keyserver.ubuntu.com
  tags: install
- name: Add repo
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
    state: present
  tags: install
- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  tags: install
- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
  tags: install
- name: Enable and start service mongod
  systemd:
    name: mongod
    state: started
    enabled: yes
  tags: install

